#!/bin/bash
APP="$1"; IMAGE="app/$APP"
# Check for wp-config.php

id=$(docker run -d $IMAGE test -f app/wp-config.php)
if [ $(docker wait $id) -ne 0 ]; then
 echo "no config"
  exit 0
fi

if [ -f "/home/dokku/.mysql/pass_$APP" ]; then
       dokku mysql:link $APP $APP
   echo "database is already linked"
else
    echo "--------> starting mysql creating"
    dokku mysql:create $APP $APP
fi
echo "ended"
